Para sub
opentensor/paratensor pull request #12
Opened 2022-10-31 16:44 UTC by SaMotlagh

- added staking (add/remove stake to the hotkey/coldkey). 
- added various tests for staking
-updated registration process and tests

2022-11-08 21:04 UTC, unconst requested changes

2022-11-08 21:04 UTC, unconst commented on pallets/paratensor/src/lib.rs
> +			BlocksPerStep::<T>::set( blocks_per_step );
This should be per netuid unless im mistaken

2022-11-08 21:04 UTC, unconst commented on pallets/paratensor/src/registration.rs
> +            uid_to_set_in_metagraph = uid_to_prune;
We should move this to its own function

2022-11-08 21:04 UTC, unconst commented on pallets/paratensor/src/registration.rs
> +                    Self::remove_global_account(&hotkey); //Hotkeys, Coldkeys
we should not be removing global account for now since they may be staked to other networks

2022-11-08 21:04 UTC, unconst commented on pallets/paratensor/src/registration.rs
> +            Self::remove_weights_from_subnet(netuid, uid_to_prune);
It might be better to instead remeber who is being pruned and do this all at once given that the bonds are going to require a full double iteration

2022-11-08 21:04 UTC, unconst commented on pallets/paratensor/src/utils.rs
> +			GlobalN::<T>::put(uid + 1);
Should be get_next_uid  for network

2022-11-09 17:22 UTC, SaMotlagh commented on pallets/paratensor/src/lib.rs
> +		/// ---- Called on the initialization of this pallet. (the order of on_finalize calls is determined in the runtime)
It is in my to do list. we will discuss it soon.

2022-11-09 17:22 UTC, SaMotlagh commented on pallets/paratensor/src/lib.rs
> +		/// --- Adds stake to a hotkey. The call is made from the
:)

2022-11-09 17:27 UTC, SaMotlagh commented on pallets/paratensor/src/registration.rs
> +            uid_to_set_in_metagraph = uid_to_prune;
I have a function to find pruning uid in line 85. This function only looks in the PrunningScores storage and find the uid to prune. This list is filled in epoch.

2022-11-09 17:29 UTC, SaMotlagh commented on pallets/paratensor/src/registration.rs
> +                    Self::remove_global_account(&hotkey); //Hotkeys, Coldkeys
in line 96 and 98 we will check that if this is the only network that hotkey was registered on. If so, then we remove the global account.

2022-11-09 19:33 UTC, SaMotlagh commented on pallets/paratensor/src/lib.rs
> +			BlocksPerStep::<T>::set( blocks_per_step );
yes, you are right. I have not worked on this part yet. it is more like a template as of now.

2022-11-10 16:20 UTC, merged